export interface Village {
    id: string;
    name: string;
    region: string;
    x: number; // Position sur la carte (0-100)
    y: number;
    description: string;
    population: string;
    rpFeatures: string[];
    dangerLevel: number; // 1-5
    hasService: boolean;
    hasGarage: boolean;
    hasRestaurant: boolean;
    hasHotel: boolean;
    hasPolice: boolean;
    hasHospital: boolean;
    landmark: string;
    quote: string;
    distanceToMontreal: number; // km
    founded: number;
}

export const villages: Village[] = [
    {
        id: "forestville",
        name: "Forestville",
        region: "Côte-Nord",
        x: 93,
        y: 12,
        description:
            "Point de départ nord de la Route 138. Dernière ville avant le fameux traversier vers Baie-Sainte-Catherine. Un coin de nature sauvage avec des routes forestières à perte de vue.",
        population: "3 100",
        rpFeatures: ["Traversier", "Routes forestières", "Pêche", "Camping sauvage", "Contrebande de bois"],
        dangerLevel: 2,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: true,
        landmark: "Le traversier Baie-Sainte-Catherine",
        quote: "« Icitte, c'est la vraie Côte-Nord, mon homme. »",
        distanceToMontreal: 450,
        founded: 1872,
    },
    {
        id: "baie-sainte-catherine",
        name: "Baie-Sainte-Catherine",
        region: "Charlevoix",
        x: 89,
        y: 20,
        description:
            "Petit village pittoresque au bout du rang. Le traversier arrive ici. Coin tranquille parfait pour les RP de pêcheurs et d'artistes.",
        population: "580",
        rpFeatures: ["Traversier", "Observation des baleines", "Petit village", "Artistes"],
        dangerLevel: 1,
        hasService: false,
        hasGarage: false,
        hasRestaurant: true,
        hasHotel: false,
        hasPolice: false,
        hasHospital: false,
        landmark: "Église historique et vue sur le fjord",
        quote: "« C'est icitte que commence le vrai Charlevoix. »",
        distanceToMontreal: 430,
        founded: 1845,
    },
    {
        id: "la-malbaie",
        name: "La Malbaie",
        region: "Charlevoix",
        x: 83,
        y: 25,
        description:
            "Ville centre de Charlevoix avec casino, golf et hôtels. Endroit parfait pour des RP de tourism, de mafia locale et de politique régionale.",
        population: "8 500",
        rpFeatures: ["Casino", "Golf", "Hôtels de luxe", "Marina", "Mafia locale", "Politique"],
        dangerLevel: 2,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: true,
        landmark: "Casino de Charlevoix & Fairmont Le Manoir",
        quote: "« Le casino, c'est là que les deals se font après minuit. »",
        distanceToMontreal: 370,
        founded: 1841,
    },
    {
        id: "baie-saint-paul",
        name: "Baie-Saint-Paul",
        region: "Charlevoix",
        x: 75,
        y: 32,
        description:
            "Capitale artistique du Québec. Galeries, boutiques, restaurants gastronomiques. Le spot parfait pour les RP d'artistes, de touristes et de secrets de village.",
        population: "7 500",
        rpFeatures: ["Galeries d'art", "Boutiques", "Restaurants chics", "Festivals", "Artistes bohèmes"],
        dangerLevel: 1,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: false,
        landmark: "Place de l'Église & galeries d'art",
        quote: "« À Baie-Saint-Paul, tout le monde connaît tout le monde... ou presque. »",
        distanceToMontreal: 310,
        founded: 1717,
    },
    {
        id: "saint-joachim",
        name: "Saint-Joachim",
        region: "Côte-de-Beaupré",
        x: 66,
        y: 38,
        description:
            "Petit village au pied du Massif. Parfait pour les amateurs de ski et de plein air. Le Mont Grand-Fonds est juste à côté.",
        population: "2 800",
        rpFeatures: ["Ski", "Plein air", "Auberges", "Sentiers de motoneige", "VTT"],
        dangerLevel: 1,
        hasService: true,
        hasGarage: false,
        hasRestaurant: true,
        hasHotel: false,
        hasPolice: false,
        hasHospital: false,
        landmark: "Le Massif de Charlevoix (vue)",
        quote: "« L'hiver, les routes sont glacées pis le monde sont chauds. »",
        distanceToMontreal: 240,
        founded: 1681,
    },
    {
        id: "chateau-richer",
        name: "Château-Richer",
        region: "Côte-de-Beaupré",
        x: 59,
        y: 42,
        description:
            "Dernier village avant Québec. Connu pour sa basilique et ses fraises. Un coin tranquille avec des secrets bien cachés.",
        population: "4 200",
        rpFeatures: ["Basilique", "Fraises", "Vergers", "Routes de campagne", "Contrabande"],
        dangerLevel: 1,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: false,
        hasPolice: true,
        hasHospital: false,
        landmark: "Basilique Sainte-Anne-de-Beaupré (proche)",
        quote: "« Les fraises sont bonnes, mais les affaires sont moins claires. »",
        distanceToMontreal: 195,
        founded: 1658,
    },
    {
        id: "quebec",
        name: "Québec",
        region: "Capitale-Nationale",
        x: 52,
        y: 48,
        description:
            "La capitale nationale! Ville fortifiée, Château Frontenac, Plaines d'Abraham. Le cœur battant du RP au Québec. Politique, crime organisé, tourisme — tout se passe icitte.",
        population: "550 000",
        rpFeatures: ["Parlement", "Château Frontenac", "Vieux-Québec", "Crime organisé", "Politique", "Tourisme", "Nightlife", "Université Laval"],
        dangerLevel: 3,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: true,
        landmark: "Château Frontenac & les Plaines d'Abraham",
        quote: "« Québec, c'est pas juste la capitale, c'est le centre du pouvoir. »",
        distanceToMontreal: 150,
        founded: 1608,
    },
    {
        id: "neuville",
        name: "Neuville",
        region: "Portneuf",
        x: 44,
        y: 52,
        description:
            "Charmant village de Portneuf avec son patrimoine historique. Coin idéal pour les RP de famille, de ferme et de mystères ruraux.",
        population: "4 700",
        rpFeatures: ["Patrimoine", "Fermes", "Érablières", "Sentiers", "Mystères ruraux"],
        dangerLevel: 1,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: false,
        hasPolice: true,
        hasHospital: false,
        landmark: "Vieux presbytère & vignobles",
        quote: "« À Neuville, on connaît l'histoire de chaque maison. »",
        distanceToMontreal: 120,
        founded: 1684,
    },
    {
        id: "trois-rivieres",
        name: "Trois-Rivières",
        region: "Mauricie",
        x: 32,
        y: 56,
        description:
            "Deuxième plus grande ville entre Québec et Montréal. Ville industrielle avec un Vieux-Très-Rivières charmant. Le spot parfait pour les RP de gang de rue, de syndicalistes et d'entrepreneurs.",
        population: "140 000",
        rpFeatures: ["Vieux-Très-Rivières", "Industrie", "Université", "Gangs de rue", "Syndicats", "Nightlife", "Festival"],
        dangerLevel: 3,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: true,
        landmark: "Vieux-Très-Rivières & les trois rivières",
        quote: "« Trois-Rivières, la ville où tu peux être tout le monde en même temps. »",
        distanceToMontreal: 80,
        founded: 1634,
    },
    {
        id: "berthierville",
        name: "Berthierville",
        region: "Lanaudière",
        x: 22,
        y: 60,
        description:
            "Petite ville de Lanaudière au bord du fleuve. Coin de campagne avec des lacs et des forêts. Parfait pour les RP de cabane à sucre, de chasse et de secrets de famille.",
        population: "4 400",
        rpFeatures: ["Lacs", "Chasse", "Cabane à sucre", "Motoneige", "Cottage life"],
        dangerLevel: 2,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: false,
        hasPolice: true,
        hasHospital: false,
        landmark: "Lac Taureau (proche) & marina",
        quote: "« L'été on va au lac, l'hiver on va dans bois. C'est simple. »",
        distanceToMontreal: 55,
        founded: 1830,
    },
    {
        id: "repentigny",
        name: "Repentigny",
        region: "Lanaudière",
        x: 14,
        y: 65,
        description:
            "Banlieue nord de Montréal en pleine expansion. Vieux-Repentigny historique vs nouvelles constructions. Le contraste parfait pour des RP de gentrification et de conflits de quartier.",
        population: "90 000",
        rpFeatures: ["Banlieue", "Vieux-Repentigny", "Nouveaux développements", "École de police", "Parc régional"],
        dangerLevel: 2,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: true,
        landmark: "Parc régional de l'Île-Lebel",
        quote: "« Repentigny, c'est là que Montréal commence sans que tu t'en rendes compte. »",
        distanceToMontreal: 25,
        founded: 1647,
    },
    {
        id: "montreal",
        name: "Montréal",
        region: "Montréal",
        x: 6,
        y: 72,
        description:
            "La métropole. Le boss final. Ville de contrastes avec le Mount-Royal, le Vieux-Port, le Quartier Latin, Hochelaga, Rosemont. Crime organisé, mafia, gangs, politique provinciale — tout converge icitte.",
        population: "2 000 000+",
        rpFeatures: ["Mafia italienne", "Gangs de rue", "Politique provinciale", "Nightlife", "Quartiers ethniques", "Université", "Port de Montréal", "Underground city"],
        dangerLevel: 5,
        hasService: true,
        hasGarage: true,
        hasRestaurant: true,
        hasHotel: true,
        hasPolice: true,
        hasHospital: true,
        landmark: "Mount Royal, Vieux-Port & Stade Olympique",
        quote: "« Montréal, c'est la jungle de béton du Québec. »",
        distanceToMontreal: 0,
        founded: 1642,
    },
];

export const regions = [
    { name: "Côte-Nord", color: "#06b6d4" },
    { name: "Charlevoix", color: "#10b981" },
    { name: "Côte-de-Beaupré", color: "#84cc16" },
    { name: "Capitale-Nationale", color: "#f59e0b" },
    { name: "Portneuf", color: "#f97316" },
    { name: "Mauricie", color: "#ef4444" },
    { name: "Lanaudière", color: "#8b5cf6" },
    { name: "Montréal", color: "#ec4899" },
];